spring:
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.naver.com
            enable: 'true'
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.naver.com
    username: ''
    port: '465'
    password: ''
    default-encoding: UTF-8
#  profiles:
#    active: prod
  datasource:
    password: '1234'
    driver-class-name: org.mariadb.jdbc.Driver
    username: web_user
    url: jdbc:mariadb://192.168.26.128:3306/myDB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  jsp-servlet:
    init-parameters:
      development: 'true'
  port: '11000'
mybatis:
  type-aliases-package: project.sln.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: 'true '
